import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Cards from "../components/Cards";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import Me from "../public/me.jpeg";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <title>MathSudre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">mathsudre</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-700 font-medium dark:text-teal-400 md:text-6xl">
              Matheus Sudré
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Desenvolvedor Front-End.
            </h3>

            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/mathsudre" target="_blank">
                <AiFillGithub />
              </a>

              <a
                href="https://www.linkedin.com/in/matheus-sudre/"
                target="_blank"
              >
                <AiFillLinkedin />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={Me} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div className="flex flex-col place-items-center">
            <h3 className="text-2xl py-2 text-teal-700 font-medium dark:text-teal-400 md:text-5xl">
              Sobre mim
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              No começo de 2022 me encontrava cursando enfermagem, mas após
              varias desilusões com a área e constatar que a mesma se encontra
              bastante desvalorizada no Brasil, decidi reviver um sonho antigo e
              decidi migrar para a área da tecnologia. Atualmente estou em
              transição de carreira especificamente para Desenvolvimento Web,
              pois sempre amei resolver problemas do dia a dia com as
              ferramentas disponíveis na internet. A tecnologia sempre esteve
              presente em minha vida, facilitando a resolução de problemas,
              sendo fonte de lazer e etc, e agora vejo que atráves da mesma
              posso estender isso e criar soluções para outras pessoas.
            </p>
          </div>

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Linguagens e Ferramentas que utilizo:
              </h3>

              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">TypeScript</p>
              <p className="text-gray-800 py-1">ReactJS</p>
              <p className="text-gray-800 py-1">HTML & CSS </p>
              <p className="text-gray-800 py-1">StyledComponents</p>
              <p className="text-gray-800 py-1">NodeJS</p>
              <p className="text-gray-800 py-1">SQL</p>
              <p className="text-gray-800 py-1">Git</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Estou aprendendo e aprimorando..
              </h3>

              <p className="text-gray-800 py-1">Docker</p>
              <p className="text-gray-800 py-1">TypeORM</p>
              <p className="text-gray-800 py-1">NodeJS</p>
              <p className="text-gray-800 py-1">Tailwind</p>
              <p className="text-gray-800 py-1">NextJS</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Projetos</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Abaixo alguns projetos Front-end desenvolvidos por mim.
            </p>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <Cards />
          </div>
        </section>
      </main>
    </div>
  );
}
